### ISSUE TITLE
Cannot use nested media queries in SSB

### ISSUE THREAD

**Issue by Kripth** [sactory/sactory#17]
Code like the following will be transpiled correctly but will fail at runtime:
```css
.content {

	width: 100%;
	height: 100vh;

	background: red;
	
	@media screen and (max-width: 1000px) {
		background: blue;
	}

}
```
