### ISSUE TITLE
Cannot use multiple properties with the same name in CSSB

### ISSUE THREAD

**Issue by Kripth** [sactory/sactory#4]
When in cssb mode only the last property overwrites the other ones with the same name.

```css
p {
    color: blue;
    color: green;
}
```
results in `p{color:green}`.

The bug affects selects too.
